version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/postgres/data/:/var/lib/postgresql/data
  movie-app:
    build:
      context: .
      dockerfile: movie-app.Dockerfile
    container_name: movies-app
    restart: unless-stopped
    privileged: true
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/movieapp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - 8080:8080
    depends_on:
      - postgres
